#!/usr/bin/env python3
"""MUTX Gap Scanner v4 — shell=False, proper gh CLI calls."""
import json, os, subprocess, time, glob
from datetime import datetime
from pathlib import Path
import os
_REPO = None
def _get_repo():
    global _REPO
    if _REPO:
        return _REPO
    # MUTX_REPO env var takes priority (for CI/cross-clone use)
    _REPO = os.environ.get("MUTX_REPO")
    if _REPO and Path(_REPO).exists():
        return _REPO
    # Fall back to repo root relative to this file
    _REPO = str(Path(__file__).resolve().parents[2])
    return _REPO
REPO = _get_repo()

GH      = "/opt/homebrew/bin/gh"
LOG     = "/Users/fortune/.openclaw/logs/gap-scanner.log"
WT      = "/Users/fortune/mutx-worktrees/factory/backend"
GH_REPO = "mutx-dev/mutx-dev"

def log(m):
    t = datetime.now().strftime("%H:%M:%S")
    line = f"[{t}] {m}"
    print(line, flush=True)
    with open(LOG, "a") as f:
        f.write(line + "\n")

def gh(args, timeout=30):
    """Run gh with args list, return json or []"""
    cmd = [GH] + args
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    try:
        return json.loads(r.stdout), r.returncode
    except:
        return [], r.returncode

def gh_text(args, timeout=30):
    """Run gh, return raw stdout string."""
    cmd = [GH] + args
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    return r.stdout.strip(), r.returncode

def git(args, cwd=WT, timeout=30):
    cmd = ["git"] + args
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd, timeout=timeout)
    return r.stdout.strip(), r.returncode

def write_signal(high, medium):
    sig_dir = Path(WT) / "signals"
    sig_dir.mkdir(exist_ok=True)
    signal_path = sig_dir / "gap-scan signal.md"
    lines = []
    lines.append("# Gap Scan Signal - " + datetime.now().strftime("%Y-%m-%d %H:%M"))
    total = len(high) + len(medium)
    lines.append("**Total findings**: {} | **High**: {} | **Medium**: {} | **Noise filtered**: 0".format(total, len(high), len(medium)))
    lines.append("")
    lines.append("## High Priority (do this week)")
    for d in high:
        lines.append("- [{}] [{}] {}".format(d["area"], d["priority"], d["description"]))
        lines.append("  | {} | effort: {}".format(d["file"], d["effort"]))
    lines.append("")
    lines.append("## Medium Priority (backlog)")
    for d in medium:
        lines.append("- [{}] [{}] {}".format(d["area"], d["priority"], d["description"]))
        lines.append("  | {} | effort: {}".format(d["file"], d["effort"]))
    lines.append("")
    lines.append("*Generated by gap-scanner v4. Signal file -- not an action queue.")
    lines.append("*CTO (CIPHER) reviews and spawns coding agents as appropriate.*")
    signal_path.write_text("\n".join(lines))
    log("Signal written: {} high, {} medium -> {}".format(len(high), len(medium), signal_path))

def main():
    log("=== Gap scanner v4 starting ===")
    high, medium = [], []

    # 1. GitHub issues: autonomy:ready / good-first-issue
    for label in ["autonomy:ready", "good-first-issue"]:
        data, rc = gh(["issue", "list", "--repo", GH_REPO, "--label", label,
                        "--state", "open", "--limit", "20", "--json", "number,title,body"])
        for issue in (data or []):
            num = issue.get("number","")
            title = issue.get("title","")
            body = issue.get("body","")[:200]
            if not title:
                continue
            pri = "p1" if "good-first" in label else "p2"
            high.append({"area": "github", "priority": pri, "description": title,
                           "file": "GitHub issue #" + str(num), "effort": "H",
                           "id": "scan-gh-" + str(num), "source": "gap-scanner:" + label})

    # 2. Stale open PRs (>7 days)
    data, rc = gh(["pr", "list", "--repo", GH_REPO, "--state", "open",
                    "--limit", "50", "--json", "number,title,createdAt"])
    for pr in (data or []):
        try:
            created = datetime.strptime(pr.get("createdAt","1970-01-01")[:10], "%Y-%m-%d")
            age = (datetime.now() - created).days
        except:
            age = 0
        if age > 7:
            pr_num = pr.get("number","")
            pr_title = pr.get("title","")[:50]
            high.append({"area": "github", "priority": "p1",
                           "description": "review: merge/close PR #" + str(pr_num) + " -- " + pr_title,
                           "file": "GitHub PR #" + str(pr_num), "effort": "H",
                           "id": "pr-stale-" + str(pr_num), "source": "gap-scanner:stale-prs"})

    # 3. SDK test coverage gaps (from worktree)
    sdk_dir = Path(WT) / "sdk" / "mutx"
    modules = {f.stem for f in sdk_dir.glob("*.py") if not f.stem.startswith("_")}
    tested = set()
    for f in (Path(WT) / "tests").glob("test_sdk_*.py"):
        name = f.stem.replace("test_sdk_", "").replace("_contract", "")
        tested.add(name)
    for mod in sorted(modules - tested):
        high.append({"area": "backend", "priority": "p2",
                       "description": "Add coverage for SDK module `{}`".format(mod),
                       "file": "sdk/mutx/" + mod + ".py", "effort": "L",
                       "id": "coverage-" + mod, "source": "gap-scanner:coverage"})

    write_signal(high, medium)
    log("=== Gap scanner done -- {} high, {} medium ===".format(len(high), len(medium)))

if __name__ == "__main__":
    main()
