// Generated by scripts/build-pico-content.mjs. Do not edit by hand.

export const PICO_GENERATED_CONTENT = {
  "generatedAt": "2026-04-16T21:56:31.886Z",
  "packSnapshot": {
    "generatedAt": "2026-04-16T21:56:31.004Z",
    "generatedOn": "2026-04-16",
    "refreshedAt": "2026-04-15",
    "docCount": 19,
    "visibleDocCount": 17,
    "lessonCount": 12,
    "totalLessonMinutes": 274,
    "sourcePaths": [
      "/Users/fortune/MUTX/src/api/knowledge/pico-builder-pack",
      "/Users/fortune/Downloads/PicoMUTX_updated_pack",
      "/Users/fortune/Downloads/agent_gpt_builder_pack 2"
    ],
    "currentProductNotes": []
  },
  "stacks": [
    {
      "id": "hermes",
      "name": "Hermes",
      "productProfile": "Hermes is the default recommendation in this pack when the user wants a persistent agent that improves over time rather than acting as a fresh stateless assistant each session.",
      "strengths": [
        "built-in learning loop",
        "persistent sessions and cross-session recall",
        "strong CLI plus gateway-oriented workflow",
        "supports multiple providers and endpoints",
        "can expose an API server for integration use cases",
        "supports profiles for isolated instances",
        "has cron / scheduled automation support",
        "has strong built-in diagnostics and state export"
      ],
      "fitSignals": [
        "“I want the best general personal agent right now.”",
        "“I want something that gets better over time.”",
        "“I want one always-on agent hub.”",
        "“I want memory, sessions, and skills.”",
        "“I want it on a VPS or an always-on mini PC.”"
      ],
      "installRealities": [
        "the official fast path is the install script documented on `hermes-agent.nousresearch.com`",
        "Linux, macOS, WSL2, and Android via Termux are the supported install targets in current docs",
        "native Windows is not the primary path; use WSL2 instead",
        "the manual path is Python/`uv`-based, with optional Node dependencies for browser or messaging extras",
        "`hermes setup` is the current full wizard; `hermes` and the messaging gateway are the two main entry points after install",
        "WSL users should prefer `hermes gateway run` over service-style `start`"
      ],
      "troubleshootingThemes": [
        "provider config mismatch",
        "gateway not running or running in the wrong mode for the platform",
        "wrong profile / wrong HERMES_HOME",
        "missing optional tool dependencies from the manual install path",
        "session or memory expectations mismatch",
        "config drift after updates",
        "remote access path not set up cleanly"
      ],
      "officialSources": [
        "https://github.com/NousResearch/hermes-agent",
        "https://github.com/NousResearch/hermes-agent/releases",
        "https://hermes-agent.nousresearch.com/docs/getting-started/installation",
        "https://hermes-agent.nousresearch.com/docs/getting-started/termux",
        "https://hermes-agent.nousresearch.com/docs/reference/cli-commands",
        "https://hermes-agent.nousresearch.com/docs/user-guide/messaging",
        "https://hermes-agent.nousresearch.com/docs/user-guide/features/api-server"
      ],
      "repoUrl": "https://github.com/NousResearch/hermes-agent",
      "docsUrl": "https://hermes-agent.nousresearch.com/docs/getting-started/installation",
      "live": {
        "stars": 93423,
        "openIssues": 4958,
        "pushedAt": "2026-04-16T21:48:52Z",
        "repoUrl": "https://github.com/NousResearch/hermes-agent",
        "latestRef": {
          "kind": "release",
          "label": "Release v2026.4.16",
          "title": "Hermes Agent v0.10.0 (2026.4.16)",
          "publishedAt": "2026-04-16T19:53:25Z",
          "url": "https://github.com/NousResearch/hermes-agent/releases/tag/v2026.4.16"
        }
      }
    },
    {
      "id": "openclaw",
      "name": "OpenClaw",
      "productProfile": "OpenClaw is the right recommendation when the user wants a broad multi-channel ecosystem, strong gateway workflow, multi-agent routing, companion apps, and a visual workspace/canvas style interface.",
      "strengths": [
        "local-first gateway controls",
        "wide messaging and channel support",
        "multi-agent routing",
        "live canvas / visual workspace",
        "onboarding-driven setup with daemon install",
        "companion apps",
        "strong channel/login workflow",
        "mobile and desktop nodes"
      ],
      "fitSignals": [
        "“I want the most integrations.”",
        "“I want companion apps and messaging.”",
        "“I want multiple channels and multiple agents.”",
        "“I want the canvas / visual workspace idea.”",
        "“I want broad ecosystem reach.”"
      ],
      "installRealities": [
        "current official materials still disagree on the minimum Node floor: the getting-started docs say Node 22.14+ while the repo README says Node 22.16+; Node 24 remains the safe target",
        "the current happy path is install first, then `openclaw onboard`; add `--install-daemon` when the user wants an always-on gateway service",
        "the current docs verify success with `openclaw gateway status` and then `openclaw dashboard`, so use those before sending the user into channel auth",
        "current docs and repo materials still expose multiple install paths, but the global install plus onboarding flow is the cleanest default for most users",
        "both native Windows and WSL2 are supported, but WSL2 is still the steadier recommendation",
        "the gateway and Control UI are separate concepts from channel auth, so verify those layers independently",
        "daemon installs are happier on a stable system Node than on `nvm` / `fnm` / `asdf` paths"
      ],
      "troubleshootingThemes": [
        "Node runtime mismatch",
        "gateway not running",
        "onboarding incomplete",
        "channel auth incomplete",
        "app or dashboard connected to the wrong gateway or wrong mode",
        "local model endpoint config issues",
        "DM pairing or allowlist policy blocking inbound use"
      ],
      "officialSources": [
        "https://github.com/openclaw/openclaw",
        "https://github.com/openclaw/openclaw/releases",
        "https://openclaw.ai/",
        "https://docs.openclaw.ai/",
        "https://docs.openclaw.ai/start/getting-started",
        "https://docs.openclaw.ai/start/onboarding",
        "https://docs.openclaw.ai/install/index",
        "https://docs.openclaw.ai/install/updating",
        "https://docs.openclaw.ai/gateway/doctor",
        "https://docs.openclaw.ai/gateway/security",
        "https://docs.openclaw.ai/gateway/tailscale",
        "https://docs.openclaw.ai/gateway/local-models"
      ],
      "repoUrl": "https://github.com/openclaw/openclaw",
      "docsUrl": "https://docs.openclaw.ai/",
      "live": {
        "stars": 358832,
        "openIssues": 18987,
        "pushedAt": "2026-04-16T21:55:31Z",
        "repoUrl": "https://github.com/openclaw/openclaw",
        "latestRef": {
          "kind": "release",
          "label": "Release v2026.4.15",
          "title": "openclaw 2026.4.15",
          "publishedAt": "2026-04-16T21:50:22Z",
          "url": "https://github.com/openclaw/openclaw/releases/tag/v2026.4.15"
        }
      }
    },
    {
      "id": "nanoclaw",
      "name": "NanoClaw",
      "productProfile": "NanoClaw is the recommendation for users who want a smaller, easier-to-audit codebase and stronger isolation via containers rather than a giant all-in-one app.",
      "strengths": [
        "lightweight mental model",
        "container isolation for agent runtime",
        "easier to understand and customize",
        "security-oriented positioning",
        "fast setup path via Claude Code and `/setup`",
        "fork-first customization model"
      ],
      "fitSignals": [
        "“I don’t want to trust a huge codebase with my whole machine.”",
        "“I want agents isolated in containers.”",
        "“I want something smaller and easier to reason about.”",
        "“I’m okay with a more builder-oriented workflow.”"
      ],
      "installRealities": [
        "the current quick start is fork or clone, `cd` into the repo, start `claude`, then run `/setup`",
        "commands prefixed with `/` are Claude Code skills and must be run inside the Claude Code prompt, not in the regular shell",
        "Node.js 20+ and Claude Code are required",
        "container support is Apple Container on macOS or Docker on macOS/Linux; Windows is effectively a WSL2 story",
        "NanoClaw is smaller and more auditable than OpenClaw, but it is also more opinionated about workflow and tooling"
      ],
      "troubleshootingThemes": [
        "Docker missing or misconfigured",
        "Claude Code missing or launched in the wrong directory",
        "`/setup` incomplete",
        "container/service startup problems",
        "wrong assumption that normal shell commands can replace Claude Code skills",
        "mismatch between expected isolation and actual host access rules"
      ],
      "officialSources": [
        "https://github.com/qwibitai/nanoclaw",
        "https://nanoclaw.dev/",
        "https://docs.nanoclaw.dev/",
        "https://docs.nanoclaw.dev/concepts/security",
        "https://docs.nanoclaw.dev/concepts/architecture",
        "https://docs.nanoclaw.dev/changelog"
      ],
      "repoUrl": "https://github.com/qwibitai/nanoclaw",
      "docsUrl": "https://docs.nanoclaw.dev/",
      "live": {
        "stars": 27394,
        "openIssues": 671,
        "pushedAt": "2026-04-16T19:59:57Z",
        "repoUrl": "https://github.com/qwibitai/nanoclaw",
        "latestRef": {
          "kind": "tag",
          "label": "Tag v1.2.0",
          "title": "v1.2.0",
          "publishedAt": "2026-04-15T11:48:50Z",
          "url": "https://github.com/qwibitai/nanoclaw/releases/tag/v1.2.0"
        }
      }
    },
    {
      "id": "picoclaw",
      "name": "PicoClaw",
      "productProfile": "PicoClaw is the recommendation for ultra-lightweight deployment, low-cost hardware, and edge-device use cases where footprint matters more than a huge ecosystem.",
      "strengths": [
        "written in Go",
        "very small resource footprint",
        "web launcher / browser-based setup path",
        "TUI launcher for headless environments",
        "model-centric provider configuration",
        "sandboxed workspace defaults",
        "good fit for low-cost hardware and edge scenarios"
      ],
      "fitSignals": [
        "“I want this on tiny hardware.”",
        "“I want the lightest possible agent stack.”",
        "“I want a launcher/web UI setup path.”",
        "“I want edge deployment more than ecosystem breadth.”"
      ],
      "installRealities": [
        "the official website download is still the recommended fast path, and the install docs now keep the core binary path separate from the heavier launcher development path",
        "the core source install in the docs is lighter than the launcher/Web UI development path: the install docs currently use a Go 1.21+ core build, so do not tell users they need the full Go + Node + pnpm stack unless they are actually building launcher/Web UI components",
        "the repo README currently calls for Go 1.25+, Node.js 22+, and pnpm 10.33.0+ for launcher / Web UI development builds",
        "the release package includes `picoclaw-launcher` for browser-based setup at `http://localhost:18800`",
        "headless installs can use `picoclaw-launcher-tui`",
        "adding `-public` to the launcher broadens exposure to other devices on the LAN, so it is not a safe default",
        "Docker and Android are now first-class documented install paths; Android APK install is a real path, with Termux as an optional fallback rather than the only Android story",
        "releases are moving quickly, so use the docs and release notes when a bug or flag may have changed recently"
      ],
      "troubleshootingThemes": [
        "config version mismatch",
        "provider config errors",
        "launcher reachable locally but not remotely because it is bound only to localhost",
        "macOS Gatekeeper blocking the unsigned launcher on first run",
        "workspace restriction surprises",
        "unsupported or incomplete edge-hardware assumptions",
        "early-development bugs",
        "user trying to disable safety boundaries too early"
      ],
      "officialSources": [
        "https://github.com/sipeed/picoclaw",
        "https://github.com/sipeed/picoclaw/releases",
        "https://picoclaw.io/",
        "https://docs.picoclaw.io/docs/",
        "https://docs.picoclaw.io/docs/getting-started/",
        "https://docs.picoclaw.io/docs/installation/",
        "https://picoclaw.io/download",
        "https://docs.picoclaw.io/docs/configuration/",
        "https://docs.picoclaw.io/docs/providers/",
        "https://docs.picoclaw.io/docs/docker/"
      ],
      "repoUrl": "https://github.com/sipeed/picoclaw",
      "docsUrl": "https://docs.picoclaw.io/docs/",
      "live": {
        "stars": 28218,
        "openIssues": 329,
        "pushedAt": "2026-04-16T17:18:47Z",
        "repoUrl": "https://github.com/sipeed/picoclaw",
        "latestRef": {
          "kind": "release",
          "label": "Release v0.2.6",
          "title": "v0.2.6",
          "publishedAt": "2026-04-08T13:39:01Z",
          "url": "https://github.com/sipeed/picoclaw/releases/tag/v0.2.6"
        }
      }
    }
  ],
  "remoteAccess": {
    "title": "Private-first remote access",
    "why": "For self-hosted agents, Tailscale is usually the safest default because it avoids the need to expose admin pages directly to the public internet.",
    "decisionDefaults": [
      "tailscale ssh for shell",
      "tailscale serve for private web apps",
      "tailscale funnel only for intentional public exposure"
    ],
    "officialSources": [
      "https://tailscale.com/docs/features/magicdns",
      "https://tailscale.com/docs/features/tailscale-ssh",
      "https://tailscale.com/docs/features/tailscale-serve",
      "https://tailscale.com/docs/reference/tailscale-cli/serve",
      "https://tailscale.com/docs/features/tailscale-funnel",
      "https://tailscale.com/docs/reference/tailscale-cli/funnel",
      "https://docs.openclaw.ai/gateway/tailscale"
    ],
    "docsUrl": "https://tailscale.com/docs/features/magicdns"
  },
  "landing": {
    "meta": {
      "title": "PicoMUTX — Guided Setup For Hermes, OpenClaw, NanoClaw, and PicoClaw",
      "description": "PicoMUTX turns 17 builder-pack playbooks, 12 guided lessons, and current repo notes across Hermes, OpenClaw, NanoClaw, and PicoClaw into one setup path."
    },
    "nav": {
      "brand": "PicoMUTX",
      "brandTag": " by MUTX",
      "cta": "Start"
    },
    "hero": {
      "badge": "Product path live now",
      "title": "Build, deploy, and govern real ",
      "titleAccent": "Hermes, OpenClaw, NanoClaw, and PicoClaw stacks without stale guesswork.",
      "subtitle": "PicoMUTX uses official install, dashboard, security, and troubleshooting docs for Hermes, OpenClaw, NanoClaw, and PicoClaw. It gives users one guided path instead of another pile of tabs.",
      "cta": "Open onboarding",
      "ctaSecondary": "See pricing",
      "meta": "Live now: onboarding, academy, tutor, support, and autopilot in one Pico flow"
    },
    "trustItems": [
      "17 builder-pack docs mapped into one product flow",
      "4 tracked stacks with live repo snapshots",
      "Safer setup: approval-aware tutoring and private-first remote access"
    ],
    "problem": {
      "eyebrow": "The Actual Friction",
      "title": "The hard part is not wanting an agent.",
      "titleLine2": "It is keeping up with changing setup details after you pick a stack.",
      "body": "Hermes, OpenClaw, NanoClaw, and PicoClaw each have different install paths, auth models, dashboards, and security traps. The product has to translate that moving reality into one sequence you can actually follow.",
      "scenarios": [
        {
          "label": "\"I do not know which stack fits my job.\"",
          "body": "Pico starts with fit, install realities, and tradeoffs instead of pretending every stack is interchangeable."
        },
        {
          "label": "\"The guide I followed is already stale.\"",
          "body": "Repo releases, runtime floors, and auth paths move fast. The platform should track those changes instead of locking copy in amber."
        },
        {
          "label": "\"My runtime works locally, but remote access feels risky.\"",
          "body": "Dashboards and launchers should not become public just because the first path was the fastest path."
        },
        {
          "label": "\"I can install things, but I still do not have a working loop.\"",
          "body": "A working agent needs lessons, tutoring, support, monitoring, and approval-aware controls that line up with each other."
        }
      ],
      "close": "That is the setup gap PicoMUTX is filling in."
    },
    "platform": {
      "eyebrow": "What The Platform Now Knows",
      "title": "One product flow fed by actual stack knowledge.",
      "body": "The app is now being filled from 17 pack docs, 12 structured lessons, and current repo notes. That means landing, onboarding, tutor, and support can explain what these stacks actually require.",
      "howItWorks": [
        {
          "title": "Compare stacks with current install and security realities",
          "body": "Use live briefs for Hermes, OpenClaw, NanoClaw, and PicoClaw instead of generic “best stack” copy divorced from official docs."
        },
        {
          "title": "Move through a real sequence from local success to control",
          "body": "The Academy already encodes the path from install, to persistence, to skills, to monitoring, to approval gates."
        },
        {
          "title": "Route blockers into evidence-first tutoring and support",
          "body": "Tutor prompts and support now begin from real failure modes pulled from the pack instead of generic motivation copy."
        },
        {
          "title": "Keep remote access private by default",
          "body": "Tailscale stays the default for dashboards, launchers, and APIs that should not be open to the public internet."
        }
      ]
    },
    "who": {
      "eyebrow": "Who This Fits",
      "title": "PicoMUTX is for users who need current setup guidance, not hype.",
      "forYouTitle": "This is for you if…",
      "notForYouTitle": "This is not for you if…",
      "forYou": [
        "You need to choose between Hermes, OpenClaw, NanoClaw, or PicoClaw with less wasted motion",
        "You want a guided install-to-operations sequence instead of stitched-together docs",
        "You care about safer remote access and approval-aware review",
        "You want tutoring and human help tied to the same underlying stack details",
        "You are willing to save real outputs instead of collecting vague setup notes"
      ],
      "notForYou": [
        "You want broad AI-agent marketing without touching the real install details",
        "You plan to expose dashboards or launchers publicly before you understand the risk boundary",
        "You already have mature internal infrastructure and only need custom enterprise governance",
        "You want a toy demo more than a runtime that survives operations",
        "You expect one frozen tutorial to stay accurate while the repos keep shipping"
      ]
    },
    "beforeAfter": {
      "eyebrow": "What Changes",
      "title": "What changes when the UI uses current stack facts",
      "beforeLabel": "Before",
      "afterLabel": "After",
      "items": [
        {
          "before": "Marketing copy talks about “AI agents” in the abstract",
          "after": "The product names Hermes, OpenClaw, NanoClaw, and PicoClaw explicitly and shows why each one exists"
        },
        {
          "before": "Onboarding is generic even when the lessons are specific",
          "after": "The first moves mirror the actual lesson objectives and saved outputs"
        },
        {
          "before": "Tutor examples are detached from current stack failure modes",
          "after": "Tutor prompts start from real install, dashboard, and launcher breakpoints"
        },
        {
          "before": "A WIP page apologizes for being empty",
          "after": "The page becomes a build ledger with tracked repos, docs, and remote-access defaults"
        }
      ],
      "close": "The point is not prettier filler. The point is a UI that stays attached to the stack reality underneath it."
    },
    "earlyAccess": {
      "eyebrow": "Current Product Flow",
      "title": "The landing now points into a real Pico product path.",
      "body": "Start in onboarding, move into the academy, use tutor when the exact next step is unclear, open support when the blocker needs a human, and use autopilot when you need live run and budget visibility.",
      "benefits": [
        "Onboarding is live as the canonical first step",
        "Academy lessons stay inside the same Pico flow",
        "Tutor keeps the lesson and stack context attached",
        "Support keeps the blocker packet and return step visible",
        "Autopilot shows live runs, spend, and gates when you sign in"
      ]
    },
    "faq": {
      "eyebrow": "Questions",
      "title": "Questions worth answering clearly",
      "items": [
        {
          "q": "Do I need to code to use PicoMUTX?",
          "a": "You still need to run real commands and verify real runtime state, but Pico is designed to turn that work into a guided setup path instead of an engineer-only maze."
        },
        {
          "q": "How does Pico decide between Hermes, OpenClaw, NanoClaw, and PicoClaw?",
          "a": "It uses fit, install realities, troubleshooting themes, and repo status pulled from the builder pack and current official sources."
        },
        {
          "q": "Does Pico replace the official docs?",
          "a": "No. It compresses them into a product path and keeps links back to the official sources so the stack details stay inspectable."
        },
        {
          "q": "Why does Tailscale keep showing up across the product?",
          "a": "Because private tailnet access is usually the safer default for dashboards, launchers, and admin pages than exposing them directly to the public internet."
        },
        {
          "q": "Will this content keep updating as the repos move?",
          "a": "Yes. The new sync path reads the local pack, optional updated packs, and live repo metadata so the content can be regenerated instead of rewritten by hand."
        }
      ]
    },
    "finalCta": {
      "eyebrow": "Open the real Pico flow",
      "title": "Do not join a list. Start the product path.",
      "body": "The fastest next step is onboarding. Pricing, tutor, support, and autopilot stay inside the same product flow after that.",
      "formHeadline": "Open onboarding",
      "formSubline": "Start with the first step now, then use tutor or human help only when the product path stops being enough.",
      "ctaButton": "Open onboarding",
      "formCtaMeta": "Live routes: onboarding, academy, tutor, support, and autopilot"
    }
  },
  "pricing": {
    "pageTitle": "Choose the product depth you actually need",
      "pageSubtitle": "The plans map to real product areas: 12 lessons, tutoring, monitored runtime context, and stack briefs across Hermes, OpenClaw, NanoClaw, and PicoClaw.",
    "pageFooter": "Current content sync tracks 17 pack docs and 4 live repos. Enterprise is for teams that need deeper rollout help, identity controls, and direct support.",
    "planDescriptions": {
      "free": "Inspect the stack map and lesson flow before you spend.",
      "starter": "Run one serious build with full academy access and tutoring.",
      "pro": "Run multiple live workflows with BYOK, stronger runtime visibility, and faster escalation.",
      "enterprise": "Roll out across a team with SSO, SLA expectations, and direct support."
    },
    "truthStrip": [
      "12 sequenced Academy lessons",
      "17 visible builder-pack docs",
      "4 tracked stack briefings",
      "Private-first remote access defaults"
    ]
  },
  "onboarding": {
    "activationChecklist": [
      {
        "chapter": "01",
        "title": "Install Hermes",
        "body": "Get one clean local Hermes install working end to end."
      },
      {
        "chapter": "02",
        "title": "Run your first agent",
        "body": "Prove the runtime can answer one bounded prompt with the provider you just configured."
      },
      {
        "chapter": "03",
        "title": "Save output",
        "body": "Hermes answers one small prompt and the transcript is saved in a file you can reopen."
      }
    ],
    "stackSpotlights": [
      {
        "id": "hermes",
        "name": "Hermes",
        "whyNow": "built-in learning loop",
        "latestSignal": "Release v2026.4.16 · Apr 16, 2026"
      },
      {
        "id": "openclaw",
        "name": "OpenClaw",
        "whyNow": "local-first gateway controls",
        "latestSignal": "Release v2026.4.15 · Apr 16, 2026"
      },
      {
        "id": "nanoclaw",
        "name": "NanoClaw",
        "whyNow": "lightweight mental model",
        "latestSignal": "Latest commit · Apr 15, 2026"
      },
      {
        "id": "picoclaw",
        "name": "PicoClaw",
        "whyNow": "written in Go",
        "latestSignal": "Repo active Unavailable"
      }
    ]
  },
  "tutor": {
    "questionProtocol": [
      "Name the exact step, command, or dashboard action you were on.",
      "Paste the evidence: output, error, transcript, or runtime state.",
      "Ask for the one next move that gets setup moving again."
    ],
    "examplePrompts": [
      "Hermes opens locally but the VPS run fails. What should I verify before changing anything?",
      "OpenClaw onboard completed, but the Control UI still does not load. What is the clean verification path?",
      "NanoClaw `/setup` ran in Claude Code, but the container path still feels broken. What should I isolate first?",
      "PicoClaw launcher works on localhost only. Should I change the bind address or keep it private with Tailscale?"
    ]
  },
  "support": {
    "lanes": [
      {
        "id": "fixing-existing",
        "title": "Stack or runtime blocker",
        "body": "Use this when a real install, lesson, dashboard, launcher, or approval step stopped in a way the product cannot close alone."
      },
      {
        "id": "other",
        "title": "Guided walkthrough",
        "body": "Use this when you need a guided session across multiple product areas instead of one isolated fix."
      }
    ],
    "escalationStandards": [
      {
        "label": "01 • Page",
        "title": "Name the stack and page",
        "body": "Say whether the problem belongs to Hermes, OpenClaw, NanoClaw, PicoClaw, Tutor, Academy, Autopilot, or the hosted account."
      },
      {
        "label": "02 • Evidence",
        "title": "Attach the setup packet",
        "body": "Bring the command, dashboard state, launcher state, or approval status that shows exactly where the path stopped."
      },
      {
        "label": "03 • Return",
        "title": "Ask for the path back into motion",
        "body": "A good escalation should end with the shortest path back into a lesson, tutor answer, or live review step."
      }
    ]
  },
  "wip": {
    "meta": {
      "title": "Live Build Ledger — PicoMUTX",
      "description": "Inspect the 17 builder-pack docs, tracked repo snapshots, and remote-access defaults now feeding the PicoMUTX experience."
    },
    "title": "Live build ledger",
    "subtitle": "This page now shows the source material feeding Pico: pack docs, Academy lessons, tracked repos, and the remote-access defaults they imply.",
    "overviewTitle": "What is already wired in",
    "overviewBody": "The content path now reads the local builder pack, optional updated pack drops, structured Academy lessons, and GitHub metadata. This page is where to inspect that feed."
  }
} as const
