#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export MUTX_SKIP_PLAYWRIGHT="${MUTX_SKIP_PLAYWRIGHT:-0}"
export MUTX_RELEASE_WEB_SMOKE="${MUTX_RELEASE_WEB_SMOKE:-1}"
export MUTX_SKIP_COMPOSE_SMOKE="${MUTX_SKIP_COMPOSE_SMOKE:-0}"
export MUTX_PLAYWRIGHT_WORKERS="${MUTX_PLAYWRIGHT_WORKERS:-1}"
export MUTX_SKIP_DESKTOP_RELEASE="${MUTX_SKIP_DESKTOP_RELEASE:-0}"

export NEXT_PUBLIC_TURNSTILE_SITE_KEY="${NEXT_PUBLIC_TURNSTILE_SITE_KEY:-ci-test-site-key}"
export TURNSTILE_SECRET_KEY="${TURNSTILE_SECRET_KEY:-ci-test-secret-key}"

echo "Running MUTX release check"
echo "- MUTX_SKIP_PLAYWRIGHT=$MUTX_SKIP_PLAYWRIGHT"
echo "- MUTX_RELEASE_WEB_SMOKE=$MUTX_RELEASE_WEB_SMOKE"
echo "- MUTX_SKIP_COMPOSE_SMOKE=$MUTX_SKIP_COMPOSE_SMOKE"
echo "- MUTX_PLAYWRIGHT_WORKERS=$MUTX_PLAYWRIGHT_WORKERS"
echo "- MUTX_SKIP_DESKTOP_RELEASE=$MUTX_SKIP_DESKTOP_RELEASE"
echo "- NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY"
echo "- TURNSTILE_SECRET_KEY=***"
echo ""

bash "$ROOT_DIR/scripts/test.sh"
