"""Generate real, stack-specific config ZIP from onboarding state.

Produces a ZIP bundle containing actual config files for the user's
chosen stack, OS, provider, and channels — not fantasy templates.
"""

from __future__ import annotations

import io
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from src.api.models.pico_onboarding import OnboardingState

KNOWLEDGE_ROOT = Path(__file__).resolve().parents[1] / "knowledge" / "pico-builder-pack"
COMMON_KB_DOCS = ("INSTALL_FLOW.md", "UPDATE_NOTES.md")
STACK_KB_DOCS = {
    "hermes": "HERMES.md",
    "openclaw": "OPENCLAW.md",
    "nanoclaw": "NANOCLAW.md",
    "picoclaw": "PICOCLAW.md",
}


# ---------------------------------------------------------------------------
# Per-stack config generators
# ---------------------------------------------------------------------------


def _build_hermes_config(state: OnboardingState) -> str:
    """Real Hermes config.yaml."""
    provider_map = {
        "openai": "openai",
        "anthropic": "anthropic",
        "google": "google",
        "local": "lm-studio",
    }
    provider = provider_map.get(state.provider, "openai")
    model_default = {
        "openai": "gpt-5-mini",
        "anthropic": "claude-sonnet-4",
        "google": "gemini-2.5-pro",
        "local": "local-model",
    }
    model = model_default.get(state.provider, "gpt-5-mini")

    channels_yaml = ""
    if state.channels:
        channels_yaml = "\n".join(f"  - {ch}" for ch in state.channels)
    else:
        channels_yaml = "  # - telegram\n  # - discord\n  # - slack"

    return f"""# Hermes Agent Configuration
# Generated by PicoMUTX Builder — {datetime.now(timezone.utc).strftime("%Y-%m-%d")}

model:
  provider: {provider}
  name: {model}
  temperature: 0.7

toolsets:
  - web
  - file
  - terminal

channels:
{channels_yaml}

terminal:
  backend: local

memory:
  enabled: true
  max_entries: 1000
"""


def _build_openclaw_config(state: OnboardingState) -> str:
    """Real openclaw.json config."""
    provider_map = {
        "openai": "openai",
        "anthropic": "anthropic",
        "google": "google",
        "local": "lm-studio",
    }
    provider = provider_map.get(state.provider, "openai")

    import json as _json

    channels = [{"name": ch, "enabled": True} for ch in (state.channels or [])]

    return (
        _json.dumps(
            {
                "version": 1,
                "provider": provider,
                "channels": channels,
                "gateway": {"enabled": True, "port": 18789},
                "dashboard": {"enabled": True},
            },
            indent=2,
        )
        + "\n"
    )


def _build_nanoclaw_compose(state: OnboardingState) -> str:
    """Real docker-compose.yml for NanoClaw."""
    return """version: "3.8"

services:
  nanoclaw:
    image: nanoclaw/agent:latest
    container_name: nanoclaw-agent
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./skills:/app/skills
    ports:
      - "127.0.0.1:3000:3000"
"""


def _build_picoclaw_config(state: OnboardingState) -> str:
    """Real PicoClaw config.json."""
    provider_map = {
        "openai": "openai",
        "anthropic": "anthropic",
        "google": "google",
        "local": "lm-studio",
    }
    provider = provider_map.get(state.provider, "openai")

    return f"""{{
  "schemaVersion": 2,
  "provider": "{provider}",
  "workspace": {{
    "sandbox": true,
    "path": "./workspace"
  }},
  "launcher": {{
    "enabled": true,
    "port": 18800
  }}
}}
"""


# ---------------------------------------------------------------------------
# Shared generators
# ---------------------------------------------------------------------------


def _build_env_template(state: OnboardingState) -> str:
    """Provider-specific .env.template."""
    lines = [
        "# API Keys — fill in your keys before running",
        "# Never commit this file or share keys in chat",
        "",
    ]

    provider_keys = {
        "openai": "OPENAI_API_KEY=sk-...",
        "anthropic": "ANTHROPIC_API_KEY=sk-ant-...",
        "google": "GOOGLE_API_KEY=AIza...",
        "local": "# LOCAL_MODEL_URL=http://127.0.0.1:1234/v1",
    }

    if state.provider:
        lines.append(provider_keys.get(state.provider, "# PROVIDER_KEY="))
    else:
        for v in provider_keys.values():
            lines.append(v)

    lines.append("")
    if state.channels:
        if "telegram" in state.channels:
            lines.append("TELEGRAM_BOT_TOKEN=")
        if "discord" in state.channels:
            lines.append("DISCORD_BOT_TOKEN=")
        if "slack" in state.channels:
            lines.append("SLACK_BOT_TOKEN=")
            lines.append("SLACK_SIGNING_SECRET=")
        if "whatsapp" in state.channels:
            lines.append("WHATSAPP_TOKEN=")

    return "\n".join(lines)


def _build_agents_md(state: OnboardingState) -> str:
    """Hermes AGENTS.md template."""
    stack_name = (state.stack or "hermes").title()
    return f"""# {stack_name} Agent Configuration

> Generated by PicoMUTX Builder

## Context
- Stack: {state.stack or "not set"}
- OS: {state.os or "not set"}
- Provider: {state.provider or "not set"}
- Goal: {state.goal or "not set"}

## Instructions
This agent helps with tasks defined by the operator.
Customize the skills and toolsets in config.yaml as needed.
"""


def _build_install_sh(state: OnboardingState) -> str:
    """OS-specific install script."""
    os_name = state.os or "linux"
    stack = state.stack or "hermes"

    lines = ["#!/usr/bin/env bash", "set -euo pipefail", "", "echo '=== PicoMUTX Setup ==='", ""]

    if stack == "hermes":
        if os_name == "macos":
            lines.append("# Install Hermes on macOS")
            lines.append("if ! command -v hermes &>/dev/null; then")
            lines.append("  curl -fsSL https://get.hermes.dev | bash")
            lines.append("fi")
            lines.append("")
            lines.append("hermes setup")
        elif os_name == "windows_wsl2":
            lines.append("# Install Hermes on WSL2")
            lines.append("if ! command -v hermes &>/dev/null; then")
            lines.append("  curl -fsSL https://get.hermes.dev | bash")
            lines.append("fi")
            lines.append("")
            lines.append("hermes setup")
        else:
            lines.append("# Install Hermes on Linux")
            lines.append("if ! command -v hermes &>/dev/null; then")
            lines.append("  curl -fsSL https://get.hermes.dev | bash")
            lines.append("fi")
            lines.append("")
            lines.append("hermes setup")
    elif stack == "openclaw":
        lines.append("# Install Node 24 (recommended)")
        if os_name == "macos":
            lines.append("brew install node@24 || true")
        else:
            lines.append("curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash -")
            lines.append("sudo apt-get install -y nodejs")
        lines.append("")
        lines.append("npm install -g openclaw")
        lines.append("openclaw onboard --install-daemon")
    elif stack == "nanoclaw":
        lines.append("# Ensure Docker is running")
        lines.append("docker info >/dev/null 2>&1 || { echo 'Docker must be running'; exit 1; }")
        lines.append("")
        lines.append("# Clone and setup")
        lines.append("git clone https://github.com/nanoclaw/nanoclaw.git")
        lines.append("cd nanoclaw")
        lines.append("# Run /setup inside Claude Code")
    elif stack == "picoclaw":
        if os_name == "macos":
            lines.append("# Download PicoClaw for macOS")
            lines.append("curl -fsSL https://picoclaw.dev/install.sh | bash")
        elif os_name == "linux":
            lines.append("# Download PicoClaw for Linux")
            lines.append("curl -fsSL https://picoclaw.dev/install.sh | bash")
        else:
            lines.append("# Download from https://picoclaw.dev")
        lines.append("")
        lines.append("picoclaw init")

    lines.append("")
    lines.append("echo 'Setup complete. Check README.md for next steps.'")

    return "\n".join(lines)


def _build_tailscale_setup(state: OnboardingState) -> str:
    """Tailscale setup script — included only when networking == tailscale."""
    return """#!/usr/bin/env bash
set -euo pipefail

echo '=== Tailscale Setup ==='

if ! command -v tailscale &>/dev/null; then
  echo 'Installing Tailscale...'
  curl -fsSL https://tailscale.com/install.sh | sh
fi

echo 'Authenticating with Tailscale...'
sudo tailscale up

echo 'Tailscale is active.'
echo '  Status: tailscale status'
echo '  Your IP: tailscale ip'
echo ''
echo 'To share a local service on your tailnet:'
echo '  tailscale serve --bg <port>'
echo ''
echo 'WARNING: tailscale funnel exposes services publicly. Do NOT use unless needed.'
"""


def _build_channel_config(channel: str, state: OnboardingState) -> tuple[str, str]:
    """Generate per-channel config snippet. Returns (filename, content)."""
    configs: dict[str, tuple[str, str]] = {
        "telegram": (
            "telegram.yaml",
            "# Telegram Bot Configuration\n"
            "# 1. Message @BotFather on Telegram to create a bot\n"
            "# 2. Copy the bot token below\n\n"
            "telegram:\n"
            "  bot_token: ${TELEGRAM_BOT_TOKEN}\n"
            "  allowed_users: []  # Add your Telegram user ID\n",
        ),
        "discord": (
            "discord.yaml",
            "# Discord Bot Configuration\n"
            "# 1. Create app at discord.com/developers/applications\n"
            "# 2. Add bot, copy token\n"
            "# 3. Invite with bot+messages.permissions\n\n"
            "discord:\n"
            "  bot_token: ${DISCORD_BOT_TOKEN}\n"
            "  allowed_guilds: []  # Add server IDs\n",
        ),
        "slack": (
            "slack.yaml",
            "# Slack App Configuration\n"
            "# 1. Create app at api.slack.com/apps\n"
            "# 2. Enable Socket Mode\n"
            "# 3. Add bot token scopes: chat:write, channels:history\n\n"
            "slack:\n"
            "  bot_token: ${SLACK_BOT_TOKEN}\n"
            "  signing_secret: ${SLACK_SIGNING_SECRET}\n",
        ),
        "whatsapp": (
            "whatsapp.yaml",
            "# WhatsApp Configuration\n"
            "# Requires WhatsApp Business API or Twilio integration\n\n"
            "whatsapp:\n"
            "  token: ${WHATSAPP_TOKEN}\n"
            "  phone_number_id: \n",
        ),
    }
    return configs.get(channel, (f"{channel}.yaml", f"# {channel} configuration\n"))


def _builder_docs_for_state(state: OnboardingState) -> list[tuple[str, str]]:
    """Return builder-pack docs that should ship inside the ZIP."""
    stack = state.stack or "hermes"
    doc_names = list(COMMON_KB_DOCS)

    stack_doc = STACK_KB_DOCS.get(stack)
    if stack_doc:
        doc_names.append(stack_doc)

    if state.networking == "tailscale":
        doc_names.append("TAILSCALE_PLAYBOOK.md")

    docs: list[tuple[str, str]] = []
    for name in doc_names:
        docs.append((f"kb/{name}", (KNOWLEDGE_ROOT / name).read_text("utf-8")))

    return docs


def _build_readme(state: OnboardingState) -> str:
    """The key deliverable — personalized install guide."""
    stack = state.stack or "hermes"
    os_name = state.os or "linux"
    provider = state.provider or "openai"

    stack_names = {
        "hermes": "Hermes",
        "openclaw": "OpenClaw",
        "nanoclaw": "NanoClaw",
        "picoclaw": "PicoClaw",
    }
    os_names = {
        "macos": "macOS",
        "linux": "Linux",
        "windows_wsl2": "Windows (WSL2)",
        "android": "Android",
    }
    provider_names = {
        "openai": "OpenAI",
        "anthropic": "Anthropic",
        "google": "Google",
        "local": "Local (LM Studio/Ollama)",
    }

    s = stack_names.get(stack, stack.title())
    o = os_names.get(os_name, os_name.title())
    p = provider_names.get(provider, provider.title())

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        f"# {s} Setup Guide",
        "",
        f"> Generated by PicoMUTX Builder on {now}",
        f"> Stack: **{s}** | OS: **{o}** | Provider: **{p}**",
        "",
        "## Quick Start",
        "",
        "### 1. Fill in your API keys",
        "",
        "Copy `.env.template` to `.env` and add your provider API key:",
        "",
        "```bash",
        "cp .env.template .env",
        "# Edit .env with your actual key",
        "```",
        "",
    ]

    if state.channels:
        ch_list = ", ".join(state.channels)
        lines += [
            "### 2. Configure channels",
            "",
            f"Channels selected: **{ch_list}**",
            "",
            "Channel config files are in the `channels/` directory.",
            "Fill in the bot tokens as described in each file.",
            "",
        ]

    lines += [
        "### 3. Run the install script",
        "",
        "```bash",
        "chmod +x install.sh",
        "./install.sh",
        "```",
        "",
        "### 4. Verify",
        "",
    ]

    verify_cmds = {
        "hermes": "hermes --version && hermes health",
        "openclaw": "openclaw --version && openclaw gateway status",
        "nanoclaw": "docker compose ps",
        "picoclaw": "picoclaw version && picoclaw status",
    }
    lines.append(f"```bash\n{verify_cmds.get(stack, 'echo check-your-setup')}\n```")

    lines += [
        "",
        "## Troubleshooting",
        "",
        "- If the install fails, check the error output carefully",
        "- Ensure your API key is valid and has credits",
        "- For networking issues, check that ports are not in use",
        "",
        "## Included Builder KB",
        "",
        "- `kb/INSTALL_FLOW.md` — current install order and verification rules used by the builder",
        f"- `kb/{STACK_KB_DOCS.get(stack, 'HERMES.md')}` — current stack-specific notes from the builder pack",
        "- `kb/UPDATE_NOTES.md` — what changed in the refreshed builder knowledge base",
        "",
        "## Need Help?",
        "",
        "Come back to **pico.mutx.dev** — your session is saved.",
        "",
        "## Security Reminder",
        "",
        "- Never share your `.env` file",
        "- Never paste API keys in chat",
        "- Keep your agent dashboard on localhost or behind Tailscale",
    ]

    if state.networking == "tailscale":
        lines += [
            "",
            "- `kb/TAILSCALE_PLAYBOOK.md` — current remote-access guidance for Tailscale",
            "",
            "## Tailscale Setup",
            "",
            "A `tailscale-setup.sh` script is included. Run it to set up private remote access.",
            "",
            "```bash",
            "chmod +x tailscale-setup.sh",
            "./tailscale-setup.sh",
            "```",
        ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def build_onboarding_package(state: OnboardingState) -> tuple[bytes, str]:
    """Generate a ZIP file with real, stack-specific config files.

    Returns:
        (zip_bytes, filename) — filename is '{stack}-setup.zip'
    """
    stack = state.stack or "hermes"
    filename = f"{stack}-setup.zip"

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # Core config per stack
        if stack == "hermes":
            zf.writestr("config.yaml", _build_hermes_config(state))
            zf.writestr("AGENTS.md", _build_agents_md(state))
        elif stack == "openclaw":
            zf.writestr("openclaw.json", _build_openclaw_config(state))
        elif stack == "nanoclaw":
            zf.writestr("docker-compose.yml", _build_nanoclaw_compose(state))
        elif stack == "picoclaw":
            zf.writestr("config.json", _build_picoclaw_config(state))
            zf.writestr(
                ".security.yml.template", "# Sensitive values go here\nprovider:\n  apiKey: \n"
            )

        # Shared files
        zf.writestr(".env.template", _build_env_template(state))
        zf.writestr("install.sh", _build_install_sh(state))
        zf.writestr("README.md", _build_readme(state))
        for archive_name, content in _builder_docs_for_state(state):
            zf.writestr(archive_name, content)

        # Channel configs
        for channel in state.channels or []:
            ch_filename, ch_content = _build_channel_config(channel, state)
            zf.writestr(f"channels/{ch_filename}", ch_content)

        # Tailscale
        if state.networking == "tailscale":
            zf.writestr("tailscale-setup.sh", _build_tailscale_setup(state))

    return buf.getvalue(), filename
