"""Generate agent config ZIP from PicoMUTX onboarding data.

Produces a ZIP bundle containing:
- agent.md  — plain-text agent manifest
- config.yaml  — structured agent configuration
- skills/README.md  — placeholder for skill modules
"""

from __future__ import annotations

import io
import zipfile
from datetime import datetime, timezone
from typing import Any


# Map onboarding pain-point selections to agent template presets
PAIN_POINT_TEMPLATES: dict[str, dict[str, Any]] = {
    "manual_repetitive": {
        "template": "task-automator",
        "description": "Automates repetitive manual tasks by chaining tool calls and scheduling.",
        "skills": ["scheduler", "file-ops", "web-scraper"],
    },
    "data_overload": {
        "template": "data-analyst",
        "description": "Ingests, summarizes, and visualizes data from multiple sources.",
        "skills": ["csv-reader", "chart-builder", "sql-query"],
    },
    "slow_support": {
        "template": "support-agent",
        "description": "Triage and respond to customer support requests with context-aware replies.",
        "skills": ["email-triage", "knowledge-search", "draft-reply"],
    },
    "scattered_knowledge": {
        "template": "knowledge-base",
        "description": "Indexes internal docs and answers questions with source citations.",
        "skills": ["doc-indexer", "semantic-search", "qa-chain"],
    },
}

DEFAULT_TEMPLATE = {
    "template": "general-purpose",
    "description": "A flexible general-purpose agent configurable via config.yaml.",
    "skills": ["web-search", "file-ops"],
}


def _resolve_template(pain_points: list[str] | None) -> dict[str, Any]:
    """Return the first matching template for a pain point, or the default."""
    if pain_points:
        for pp in pain_points:
            if pp in PAIN_POINT_TEMPLATES:
                return PAIN_POINT_TEMPLATES[pp]
    return DEFAULT_TEMPLATE


def _build_agent_md(
    *,
    agent_name: str,
    template: dict[str, Any],
    pain_points: list[str] | None,
    user_email: str | None,
) -> str:
    """Build the agent.md manifest."""
    now = datetime.now(timezone.utc).isoformat()
    pp_lines = ""
    if pain_points:
        pp_lines = "\n".join(f"- {pp}" for pp in pain_points)
        pp_lines = f"\n{pp_lines}\n"

    no_pp_default = "- (none specified)\n"

    return f"""# {agent_name}

> Generated by PicoMUTX onboarding — {now}

## Overview

Template: **{template["template"]}**
{template["description"]}

## Pain Points Addressed
{pp_lines if pp_lines.strip() else no_pp_default}
## Owner

{user_email or "(unknown)"}

## Next Steps

1. Review `config.yaml` and adjust parameters.
2. Add custom skills under `skills/`.
3. Deploy with `mutx deploy {agent_name}`.
"""


def _build_config_yaml(
    *,
    agent_name: str,
    template: dict[str, Any],
    model: str | None,
) -> str:
    """Build the config.yaml configuration."""
    skills_list = template.get("skills", [])
    skills_yaml = "\n".join(f"  - {s}" for s in skills_list)

    return f"""# Agent configuration for {agent_name}
# Generated by PicoMUTX

agent:
  name: "{agent_name}"
  template: "{template["template"]}"
  description: |
    {template["description"]}
  model: "{model or "gpt-4o-mini"}"
  temperature: 0.7
  max_tokens: 4096

skills:
{skills_yaml}

runtime:
  timeout_seconds: 300
  max_retries: 3
  log_level: info
"""


def _build_skills_readme(template: dict[str, Any]) -> str:
    """Build the skills/README.md."""
    skills_list = template.get("skills", [])
    skills_section = "\n".join(f"- **{s}**" for s in skills_list)

    return f"""# Skills

Place skill module files here. Each skill is a Python module or YAML spec
that the agent can invoke at runtime.

## Bundled Skills

{skills_section}

## Adding a Custom Skill

1. Create a new file: `skills/my_skill.py`
2. Implement the skill interface (see docs).
3. Add `- my_skill` to `skills:` in `config.yaml`.
"""


def generate_package_zip(
    *,
    agent_name: str,
    pain_points: list[str] | None = None,
    model: str | None = None,
    user_email: str | None = None,
) -> bytes:
    """Generate a ZIP file containing the agent config package.

    Returns:
        bytes: The raw ZIP file content.
    """
    template = _resolve_template(pain_points)

    agent_md = _build_agent_md(
        agent_name=agent_name,
        template=template,
        pain_points=pain_points,
        user_email=user_email,
    )
    config_yaml = _build_config_yaml(
        agent_name=agent_name,
        template=template,
        model=model,
    )
    skills_readme = _build_skills_readme(template)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("agent.md", agent_md)
        zf.writestr("config.yaml", config_yaml)
        zf.writestr("skills/README.md", skills_readme)

    return buf.getvalue()
