apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mutx
  labels:
    app.kubernetes.io/name: mutx
    app.kubernetes.io/instance: mutx
    helm.sh/chart: mutx-0.1.0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mutx
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
