{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mutx.fullname" . }}-env
  labels:
    {{- include "mutx.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secretEnv | nindent 2 }}
{{- end }}
